CREATE TABLE reminders(
id INT PRIMARY KEY,
userID VARCHAR(30) NOT NULL,
remindTime TIMESTAMP,
message VARCHAR(255)
);

CREATE TABLE sheets(
  id INT PRIMARY KEY,
  userID VARCHAR(30) NOT NULL,
  link VARCHAR (255)
);