CREATE TABLE reminders(
id SERIAL PRIMARY KEY ,
userID VARCHAR(30) NOT NULL,
remindTime TIMESTAMPTZ,
message VARCHAR(255)
);

CREATE TABLE sheets(
  id SERIAL PRIMARY KEY,
  userID VARCHAR(30) NOT NULL,
  link VARCHAR (255)
);